import type { DefinicionLogro } from "@/lib/gamificacion/types";

/**
 * DEFINICIÓN DE LOGROS
 * ~30 logros organizados por categoría.
 */
export const LOGROS: DefinicionLogro[] = [
  // ─── Primeros Pasos ─────────────────────────────────────────
  {
    id: "primer-paso",
    nombre: "Primer Paso",
    descripcion: "Completaste tu primer quiz",
    icono: "🎓",
    xpBonus: 25,
    condicion: "Completar cualquier quiz",
    categoria: "general",
  },
  {
    id: "lector-novato",
    nombre: "Lector Novato",
    descripcion: "Leíste tu primer tema",
    icono: "📖",
    xpBonus: 25,
    condicion: "Marcar un tema como leído",
    categoria: "general",
  },
  {
    id: "explorador-curioso",
    nombre: "Explorador Curioso",
    descripcion: "Probaste quizzes de distintos temas",
    icono: "🎪",
    xpBonus: 50,
    condicion: "Completar quizzes de al menos 3 temas diferentes",
    categoria: "general",
  },

  // ─── Maestría ───────────────────────────────────────────────
  {
    id: "francotirador",
    nombre: "Francotirador",
    descripcion: "Obtuviste 100% en un quiz",
    icono: "🎯",
    xpBonus: 50,
    condicion: "Obtener puntaje perfecto en cualquier quiz",
    categoria: "general",
  },
  {
    id: "raton-biblioteca",
    nombre: "Ratón de Biblioteca",
    descripcion: "Leíste todos los temas de una materia",
    icono: "📚",
    xpBonus: 100,
    condicion: "Marcar todos los temas de una materia como leídos",
    categoria: "materia",
  },
  {
    id: "sin-piedad",
    nombre: "Sin Piedad",
    descripcion: "Obtuviste 100% en un Boss Battle",
    icono: "💀",
    xpBonus: 150,
    condicion: "Puntaje perfecto en un Boss Battle",
    categoria: "general",
    oculto: true,
  },

  // ─── Consistencia (Rachas) ──────────────────────────────────
  {
    id: "racha-3",
    nombre: "Constante",
    descripcion: "Racha de 3 días consecutivos",
    icono: "🔥",
    xpBonus: 50,
    condicion: "Estudiar 3 días seguidos",
    categoria: "general",
  },
  {
    id: "racha-7",
    nombre: "En Llamas",
    descripcion: "Racha de 7 días consecutivos",
    icono: "🔥",
    xpBonus: 150,
    condicion: "Estudiar 7 días seguidos",
    categoria: "general",
  },
  {
    id: "racha-14",
    nombre: "Imparable",
    descripcion: "Racha de 14 días consecutivos",
    icono: "⚡",
    xpBonus: 300,
    condicion: "Estudiar 14 días seguidos",
    categoria: "general",
  },
  {
    id: "racha-30",
    nombre: "Leyenda Viviente",
    descripcion: "Racha de 30 días consecutivos",
    icono: "👑",
    xpBonus: 500,
    condicion: "Estudiar 30 días seguidos",
    categoria: "general",
    oculto: true,
  },

  // ─── Volumen ────────────────────────────────────────────────
  {
    id: "50-preguntas",
    nombre: "Calentando Motores",
    descripcion: "Respondiste 50 preguntas",
    icono: "💪",
    xpBonus: 50,
    condicion: "Responder 50 preguntas en total",
    categoria: "general",
  },
  {
    id: "100-preguntas",
    nombre: "Centenario",
    descripcion: "Respondiste 100 preguntas",
    icono: "💯",
    xpBonus: 100,
    condicion: "Responder 100 preguntas en total",
    categoria: "general",
  },
  {
    id: "500-preguntas",
    nombre: "Cerebro de Acero",
    descripcion: "Respondiste 500 preguntas",
    icono: "🧠",
    xpBonus: 300,
    condicion: "Responder 500 preguntas en total",
    categoria: "general",
  },
  {
    id: "1000-preguntas",
    nombre: "Máquina de Conocimiento",
    descripcion: "Respondiste 1000 preguntas",
    icono: "🤖",
    xpBonus: 500,
    condicion: "Responder 1000 preguntas en total",
    categoria: "general",
    oculto: true,
  },
  {
    id: "10-quizzes",
    nombre: "Entrenamiento Básico",
    descripcion: "Completaste 10 quizzes",
    icono: "📝",
    xpBonus: 75,
    condicion: "Completar 10 quizzes",
    categoria: "general",
  },
  {
    id: "25-quizzes",
    nombre: "Veterano",
    descripcion: "Completaste 25 quizzes",
    icono: "🎖️",
    xpBonus: 150,
    condicion: "Completar 25 quizzes",
    categoria: "general",
  },
  {
    id: "50-quizzes",
    nombre: "Coleccionista",
    descripcion: "Completaste 50 quizzes",
    icono: "💎",
    xpBonus: 300,
    condicion: "Completar 50 quizzes",
    categoria: "general",
  },

  // ─── Boss Battles ───────────────────────────────────────────
  {
    id: "matadragones",
    nombre: "Matadragones",
    descripcion: "Derrotaste tu primer Boss Battle",
    icono: "🐉",
    xpBonus: 100,
    condicion: "Aprobar un Boss Battle",
    categoria: "general",
  },
  {
    id: "cazador-jefes",
    nombre: "Cazador de Jefes",
    descripcion: "Derrotaste 4 Boss Battles",
    icono: "⚔️",
    xpBonus: 200,
    condicion: "Aprobar 4 Boss Battles",
    categoria: "general",
  },

  // ─── Velocidad ──────────────────────────────────────────────
  {
    id: "rayo",
    nombre: "Rayo",
    descripcion: "Completaste un quiz en menos de 2 minutos",
    icono: "⚡",
    xpBonus: 75,
    condicion: "Terminar un quiz en menos de 120 segundos",
    categoria: "general",
  },
  {
    id: "flash",
    nombre: "Flash",
    descripcion: "Completaste un quiz en menos de 1 minuto",
    icono: "💨",
    xpBonus: 150,
    condicion: "Terminar un quiz en menos de 60 segundos",
    categoria: "general",
    oculto: true,
  },

  // ─── Por materia: Psicoestadística Descriptiva ──────────────
  {
    id: "pde-todas-lecturas",
    nombre: "Teórico Completo",
    descripcion: "Leíste todos los temas de Psicoestadística Descriptiva",
    icono: "📊",
    xpBonus: 150,
    condicion: "Completar todas las lecturas de PDE",
    categoria: "materia",
  },
  {
    id: "pde-todas-quests",
    nombre: "Maestro Estadístico",
    descripcion: "Completaste TODAS las quests de Psicoestadística Descriptiva",
    icono: "🏆",
    xpBonus: 500,
    condicion: "Completar todas las quests de PDE-111",
    categoria: "materia",
  },
  {
    id: "pde-t1-maestro",
    nombre: "Escalas Dominadas",
    descripcion: "Completaste todas las quests del Tema 1",
    icono: "📐",
    xpBonus: 100,
    condicion: "Completar las 4 quests del Tema 1 de PDE",
    categoria: "materia",
  },
  {
    id: "pde-t4-maestro",
    nombre: "Maestro Bidimensional",
    descripcion: "Completaste todas las quests del Tema 4",
    icono: "📈",
    xpBonus: 100,
    condicion: "Completar las 4 quests del Tema 4 de PDE",
    categoria: "materia",
  },

  // ─── Niveles ────────────────────────────────────────────────
  {
    id: "nivel-5",
    nombre: "Competente Certificado",
    descripcion: "Alcanzaste el nivel 5",
    icono: "🧮",
    xpBonus: 100,
    condicion: "Llegar al nivel 5 (Competente)",
    categoria: "general",
  },
  {
    id: "nivel-8",
    nombre: "Maestría Alcanzada",
    descripcion: "Alcanzaste el nivel 8",
    icono: "🧠",
    xpBonus: 200,
    condicion: "Llegar al nivel 8 (Maestro)",
    categoria: "general",
  },
  {
    id: "nivel-10",
    nombre: "Iluminación Total",
    descripcion: "Alcanzaste el nivel máximo",
    icono: "🌟",
    xpBonus: 500,
    condicion: "Llegar al nivel 10 (Iluminado)",
    categoria: "general",
    oculto: true,
  },

  // ─── Secretos ───────────────────────────────────────────────
  {
    id: "noctambulo",
    nombre: "Noctámbulo",
    descripcion: "Completaste un quiz después de la medianoche",
    icono: "🦉",
    xpBonus: 50,
    condicion: "Hacer un quiz entre las 00:00 y las 05:00",
    categoria: "secreto",
    oculto: true,
  },
  {
    id: "madrugador",
    nombre: "Madrugador",
    descripcion: "Completaste un quiz antes de las 7 AM",
    icono: "🌅",
    xpBonus: 50,
    condicion: "Hacer un quiz entre las 05:00 y las 07:00",
    categoria: "secreto",
    oculto: true,
  },
];
